name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDg2M2JjNTctOWU0ZC00ZGIyLWIyYTgtM2E2YTVhZmJkMWJlIiwidGVuYW50X2lkIjoiMDliZWM4YTk1NzNhZTlhODhjNzRmNDhhMDc0ZGFjM2FhMDJkNGQ0OWQ5YTM4MmQ4ZTRmMmNlMTdlZmRjODQ3MiIsImludGVybmFsX3NlY3JldCI6IjQ3OTdlMWQ3LWIzOTMtNGY5My1hMjRiLWQ2NzZjNGM3YTA2NiJ9.J6xkbGRH_dqvL3lREA3GaWib-aTMVJO8vHQOy07-nWU"
JWT_SECRET ="rakesh"
